In [3]:
from numpy import *

In [2]:
a = array([[2.5, 2.4], [0.5, .7], [2.2, 2.9], [1.9, 2.2], [3.1, 3.], [2.3, 2.7],
          [2., 1.6], [1., 1.1], [1.5, 1.6], [1.1, .9]])

In [6]:
average(a, axis=0)

array([ 1.81,  1.91])

In [7]:
b = a - average(a, axis=0)

In [8]:
b

array([[ 0.69,  0.49],
       [-1.31, -1.21],
       [ 0.39,  0.99],
       [ 0.09,  0.29],
       [ 1.29,  1.09],
       [ 0.49,  0.79],
       [ 0.19, -0.31],
       [-0.81, -0.81],
       [-0.31, -0.31],
       [-0.71, -1.01]])

In [12]:
c = cov(b.T)
c

array([[ 0.61655556,  0.61544444],
       [ 0.61544444,  0.71655556]])

In [13]:
linalg.eig(c)

(array([ 0.0490834 ,  1.28402771]), array([[-0.73517866, -0.6778734 ],
        [ 0.6778734 , -0.73517866]]))

In [14]:
eigenvalues = linalg.eig(c)[0]
eigenvectors = linalg.eig(c)[1]
print eigenvalues
print eigenvectors

[ 0.0490834   1.28402771]
[[-0.73517866 -0.6778734 ]
 [ 0.6778734  -0.73517866]]


In [15]:
argsort(eigenvalues)

array([0, 1], dtype=int64)

In [21]:
num = 1
eigenvs = eigenvectors[:, argsort(eigenvalues).tolist()[::-1][:num]]
eigenvs

array([[-0.6778734 ],
       [-0.73517866]])

In [27]:
finaldata = b.dot(eigenvs)
finaldata

array([[-0.82797019],
       [ 1.77758033],
       [-0.99219749],
       [-0.27421042],
       [-1.67580142],
       [-0.9129491 ],
       [ 0.09910944],
       [ 1.14457216],
       [ 0.43804614],
       [ 1.22382056]])

In [4]:
logspace(-4, 4, 3)

array([  1.00000000e-04,   1.00000000e+00,   1.00000000e+04])